dist: trusty
sudo: false
language: python
python:
- "2.6"
- "2.7"
- pypy
before_install:
- pyflakes=pyflakes
- if [[ $TRAVIS_PYTHON_VERSION = 2.6 ]]; then pyflakes='pyflakes<2'; fi
- if [[ $TRAVIS_PYTHON_VERSION = 2.6 ]]; then sphinx_suffix===1.4.9; fi
install:
- pip install pydiatra $pyflakes
- pip install sphinx${sphinx_suffix}
script:
- py2diatra .
- pyflakes .
- PYTHONPATH=$PWD sphinx-build -b doctest doc tmp
- python setup.py install
- cd /
- python -c 'import dime'

# vim:ts=2 sts=2 sw=2 et
